---
title: 'CREATE: Visualization Project'
author: "Charles Lang"
date: "March 29, 2016"
output: html_document
---
#Setup
```{r, echo=TRUE}
#Libraries
library(foreign)
library(tidyr)
library(dplyr)
library(corrgram)
library(ggplot2)

#Upload Pre-Post Data
PREPOST <- as.data.frame(read.spss("BIS_Spring2014_8.15.14.sav"))

#Upload game viz data
V1 <- read.csv("C2L3processed.csv")
V1$chapter <- 2
V1$level <- 3
V2 <- read.csv("C2L5processed.csv")
V2$chapter <- 2
V2$level <- 5
V3 <- read.csv("C2L6processed.csv")
V3$chapter <- 2
V3$level <- 6
V4 <- read.csv("C2L7processed.csv")
V4$chapter <- 2
V4$level <- 7
V5 <- read.csv("C3L3processed.csv")
V5$chapter <- 3
V5$level <- 5

VIZ <- dplyr::bind_rows(V1,V2,V3,V4,V5)

#Subset variables
PREPOST <- dplyr::select(PREPOST, ID, PreGeoSum, PostGeoSum, PrePostGeoGain)

#Merge Viz data with Pre-Post
D1 <- dplyr::inner_join(PREPOST, VIZ, by = "ID")

```
#Exploratory Visualizations
```{r}
#Correlogram
COR <- D1
COR$ID <- NULL
COR$chapter <- NULL
COR$level <- NULL
COR$BADGE_OPT <- NULL
COR$LEVEL_ENDED <- NULL

corrgram(COR, order=TRUE, lower.panel=panel.ellipse,
  upper.panel=panel.pts, text.panel=panel.txt,
  diag.panel=panel.minmax)

#Boxplot
BOX <- tidyr::gather(D1, "variable", "measures", 5:14)

p1 <- ggplot(BOX, aes(measures, PrePostGeoGain))
p1 + geom_boxplot() + facet_wrap(~variable, scales = "free") + theme(axis.text.x  = element_text(angle=60, vjust=0.5, size=7)) + xlab("")

p2 <- ggplot(BOX, aes(measures, PreGeoSum))
p2 + geom_boxplot() + facet_wrap(~variable, scales = "free") + theme(axis.text.x  = element_text(angle=60, vjust=0.5, size=7)) + xlab("")

p3 <- ggplot(BOX, aes(measures, PostGeoSum))
p3 + geom_boxplot() + facet_wrap(~variable, scales = "free") + theme(axis.text.x  = element_text(angle=60, vjust=0.5, size=7)) + xlab("")

```


```{r}

```

